-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [double_and_add]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace double_and_add

/-- Trait declaration: [core::ops::arith::Add]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 76:0-76:31
    Name pattern: [core::ops::arith::Add]
    Visibility: public -/
@[rust_trait "core::ops::arith::Add"]
structure core.ops.arith.Add (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  add : Self → Rhs → Result Self_Output

/-- Trait declaration: [num_traits::identities::Zero]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/num-traits-0.2.19/src/identities.rs', lines 12:0-12:48
    Name pattern: [num_traits::identities::Zero]
    Visibility: public -/
@[rust_trait "num_traits::identities::Zero"
  (parentClauses := ["coreopsarithAddInst"])]
structure num_traits.identities.Zero (Self : Type) where
  coreopsarithAddInst : core.ops.arith.Add Self Self Self
  zero : Result Self
  is_zero : Self → Result Bool

/-- [double_and_add::double_and_add]:
    Source: 'src/lib.rs', lines 9:0-23:1
    Visibility: public -/
def double_and_add
  {T : Type} (num_traitsidentitiesZeroInst : num_traits.identities.Zero T)
  (coremarkerCopyInst : core.marker.Copy T) (base : T) (scalar : Std.U64) :
  Result T
  := do
  if scalar = 0#u64
  then num_traitsidentitiesZeroInst.zero
  else
    let i ← scalar / 2#u64
    let half ←
      double_and_add num_traitsidentitiesZeroInst coremarkerCopyInst base i
    let i1 ← scalar % 2#u64
    if i1 = 1#u64
    then
      let t ← num_traitsidentitiesZeroInst.coreopsarithAddInst.add half half
      num_traitsidentitiesZeroInst.coreopsarithAddInst.add t base
    else num_traitsidentitiesZeroInst.coreopsarithAddInst.add half half
partial_fixpoint

end double_and_add
